# Generated by Django 5.2.7 on 2025-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_type', models.CharField(choices=[('pending', 'Pending Approval'), ('state', 'State Consultant'), ('district', 'District Consultant')], default='pending', max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='consultants/profile/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='consultants/id_proofs/')),
                ('qualification_certificate', models.FileField(blank=True, null=True, upload_to='consultants/certificates/')),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='consultants/experience/')),
                ('verified', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
