# Generated by Django 5.2.7 on 2025-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_documents', models.FileField(blank=True, null=True, upload_to='applications/docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('college_review', 'College Reviewing'), ('accepted', 'Accepted by College'), ('awaiting_payment', 'Awaiting Booking Payment'), ('confirmed', 'Seat Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colleges/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('college_code', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('about_college', models.TextField(blank=True, max_length=1000)),
                ('college_logo', models.ImageField(blank=True, null=True, upload_to='colleges/logo/')),
                ('college_image', models.ImageField(blank=True, null=True, upload_to='colleges/main/')),
                ('credential_image', models.ImageField(blank=True, null=True, upload_to='colleges/credentials/')),
                ('verified', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('affiliation_details', models.CharField(blank=True, max_length=255, null=True)),
                ('eligibility', models.CharField(max_length=255)),
                ('fees_structure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consultancy_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_on_demand', models.BooleanField(default=False)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('admission_completed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('after_10th', 'After 10th'), ('after_12th', 'After 12th'), ('bachelor', 'After Bachelor'), ('master', 'Master Level')], default='after_12th', max_length=30)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name for frontend UI', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
                'ordering': ['level', 'name'],
            },
        ),
    ]
