# Generated by Django 5.2.7 on 2025-11-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegegallery',
            name='college',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.RemoveField(
            model_name='collegeprofile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='collegeprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='accreditation_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='college_type',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('autonomous', 'Autonomous')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='official_registration_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='about_college',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdmissionApplication',
        ),
        migrations.DeleteModel(
            name='CollegeGallery',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
