# Generated by Django 5.2.7 on 2025-11-13 04:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_remove_collegegallery_college_remove_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(help_text="e.g., '4 Years', '2 Years'", max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Enter total course fee', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('eligibility', models.TextField(blank=True, help_text='Minimum qualification required')),
                ('description', models.TextField(blank=True, null=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='courses/brochures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='College.collegeprofile', to_field='college_code')),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('college', 'name', 'specialization')},
            },
        ),
    ]
