# Generated by Django 5.2.7 on 2025-11-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0009_hostel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('ba', 'BA'), ('llb', 'LLB'), ('mba', 'MBA'), ('mbbs', 'MBBS')], default='btech', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='main_stream',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('law', 'Law'), ('finance', 'Finance'), ('medical', 'Medical'), ('arts', 'Arts')], max_length=50, default='engineering'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['degree', 'specialization']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('college', 'degree', 'specialization', 'level')},
        ),
    ]
