# Generated by Django 5.2.7 on 2025-11-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consultant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('10', '10th Grade'), ('12', '12th Grade'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('other', 'Other')], max_length=20, null=True)),
                ('school_college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage_or_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=10, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/profile_photos/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='students/id_proofs/')),
                ('last_mark_sheet', models.FileField(blank=True, null=True, upload_to='students/mark_sheets/')),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='Consultant.consultantprofile')),
            ],
        ),
    ]
