# Generated by Django 5.2.7 on 2025-11-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_email_verified_user_phone_verified_emailotp_and_more'),
    ]

    operations = [
    ]
