# Generated by Django 5.2.7 on 2025-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20251105_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name', 'email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Full name of student/consultant or institution name', max_length=255, null=True),
        ),
    ]
