# Generated by Django 5.2.7 on 2025-11-05 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_options_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('consultant', 'Consultant'), ('college', 'College'), ('counsellor', 'Counsellor'), ('admin', 'Admin')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrePhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to='User.preregistration')),
            ],
        ),
        migrations.CreateModel(
            name='PreEmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to='User.preregistration')),
            ],
        ),
    ]
