# Generated by Django 5.2.7 on 2025-11-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_preregistration_prephoneotp_preemailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='True if profile setup is complete'),
        ),
    ]
